:filetype off
:call pathogen#runtime_append_all_bundles()
:call pathogen#helptags()
:set viminfo='10,\"100,:20,%,n~/.viminfo
:set wrap
:set number
:color ron
:set background=dark
:set ignorecase
:syntax on
:filetype on
:filetype plugin indent on
:let g:pylint_onwrite=0
:set autoindent
:set smartindent
:set tabstop=4
:set shiftwidth=4
:set noexpandtab
:map <c-j> <c-w>j
:map <c-k> <c-w>k
:map <c-l> <c-w>l
:map <c-h> <c-w>h
:set mouse=a
:map <leader>n :NERDTreeToggle<CR>
":set foldcolumn=3
:set backspace=indent,eol,start
:set hlsearch
:set ruler
"autocmd VimEnter * NERDTree
"autocmd VimEnter * wincmd p
"

function! ResCur()
	if line("'\"") <= line("$")
		normal! g`"
		return 1
	endif
endfunction

augroup resCur
	autocmd!
	autocmd BufWinEnter * call ResCur()
augroup END
