:filetype off
:call pathogen#runtime_append_all_bundles()
:call pathogen#helptags()
:set wrap
:set number
:color ron
:set background=dark
:set ignorecase
:syntax on
:filetype on
:filetype plugin indent on
:set autoindent
:set smartindent
:set tabstop=4
:set shiftwidth=4
:set noexpandtab
:map <c-j> <c-w>j
:map <c-k> <c-w>k
:map <c-l> <c-w>l
:map <c-h> <c-w>h
:let g:pylint_onwrite=0
:set mouse=a
:map <leader>n :NERDTreeToggle<CR>
:set foldcolumn=3
"autocmd VimEnter * NERDTree
"autocmd VimEnter * wincmd p
